version: '2.0'

services:
  quotes-hasher-service:
    container_name: quotes-hasher-service
    build: ../BackEnd/
    command: ./wait-for-it.sh quotes-mysql:3306 -t 60 -- bash -c 'npx nodemon index.js' 
    volumes:
      - ../BackEnd:/home/node/app
    env_file:
      - ./.env

  quotes-initializer:
    container_name: quotes-initializer
    image: mysql
    volumes:
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh quotes-mysql:3306 -t 60 -- bash -c 'mysql -h quotes-mysql -uroot -pslpass < /scripts/init_db.sql'

  quotes-mysql:
    container_name: quotes-mysql
    image: mysql
    expose:
      - '3306'
    env_file:
      - ./.env

  backend-for-frontend:
    container_name: quotes-backend-for-frontend
    command: ./scripts/wait-for-it.sh quotes-mysql:3306 -t 60 -- bash -c 'npx nodemon index.js' 
    volumes:
      - ./:/home/node/app/
    build: .
    ports:
      - '3001:3001'
    env_file:
      - ./.env

  quotes-data-filler:
    container_name: quotes-data-filler
    command: ./wait-for-it.sh quotes-mysql:3306 -t 60 -- bash -c 'sleep 20 && yarn start' 
    build: ../DataFiller/
    env_file:
      - ./.env

  quotes-message-queue:
    container_name: quotes-message-queue
    image: rabbitmq
    expose:
      - '5672'
    hostname: quotes-rabbitmq